export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  console.log("montando layout"); // Mensagem no console para debug
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
