import Link from 'next/link'; // Importação necessária para usar o componente Link

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/novarota">Nova Rota</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
