import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/rota1">Rota 1</Link>
            </li>
            <li>
              <Link href="/rota2">Rota 2</Link>
            </li>
            <li>
              <Link href="/rota3">Rota 3</Link>
            </li>
            <li>
              <Link href="/rota4">Rota 4</Link>
            </li>
            <li>
              <Link href="/rota5">Rota 5</Link>
            </li>
            <li>
              <Link href="/movies">Movies</Link>
            </li>
            <li>
              <Link href="/movieSearch">Movies Search</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
